# templates/applications.yaml
{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ . }}
  namespace: {{ $.Values.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $.Values.spec.destination.namespace }}
    name: {{ $.Values.spec.destination.name }}
  project: default
  source:
    path: {{ $.Values.spec.source.path }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}

    helm:
      valueFiles: {{ $.Values.helm.valuesFiles }}
      parameters:
        - name: image.tag
          value: {{ $.Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
{{- end }}