# templates/applications.yaml
{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .spec.destination.namespace }}
    name: {{ .spec.destination.name }}
  project: default
  source:
    path: {{ .spec.source.path }}
    repoURL: {{ .spec.source.repoURL }}
    targetRevision: {{ .spec.source.targetRevision }}

    helm:
      valueFiles: {{ .spec.source.helm.valuesFiles }}
      parameters:
        - name: image.tag
          value: {{ .spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
{{- end }}