applications:
  guestbook:
    enable: true
    spec:
      source:
        targetRevision: 7f9b04f0af92131ef99a4093887c093bc23dcdac
        imagetag: "0.2"

  guestbook2:
    spec:
      source:
        imagetag: "0.2"