applications:
  guestbook:
    enable: true
    spec:
      source:
        targetRevision: 6b4dbc58cf5b602410a5a943ee9272c73a56094c
        imagetag: "0.2"

  guestbook2:
    spec:
      source:
        imagetag: "0.2"