
applications:
  guestbook:
    enable: true
    namespace: guestbook
    spec:
      destination:
        name: in-cluster
        namespace: guestbook
      source:
        path: guestbook
        repoURL: https://github.com/jrcast/argocdtest.git
        targetRevision: main
        helm:
          valuesFiles:
          - values.yaml
          - configs.yaml
