
applications:
  guestbook:
    enable: false
    namespace: argocd
    spec:
      destination:
        name: in-cluster
        namespace: guestbook
      source:
        path: guestbook
        repoURL: https://github.com/jrcast/argocdtest.git
        targetRevision: main
        helm:
          valuesFiles:
          - values.yaml
          - configs.yaml



  guestbook2:
    enable: false
    namespace: argocd
    spec:
      destination:
        name: in-cluster
        namespace: guestbook2
      source:
        path: guestbook
        repoURL: https://github.com/jrcast/argocdtest.git
        targetRevision: main
        helm:
          valuesFiles:
          - values.yaml
          - configs.yaml