apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: guestbook
  name: guestbook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: guestbook-ui
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false

---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
